# Generated by Django 6.0.4 on 2026-04-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='processtomake',
            field=models.TextField(blank=True),
        ),
    ]
